### ISSUE TITLE
python报错

### ISSUE THREAD

**Issue by gewplay** [chenjiandongx/magnet-dht#12]
[root@fox magnet-dht]# python manage.py
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    from magnet_dht.crawler import start_server
  File "/root/magnet-dht/magnet_dht/crawler.py", line 13, in <module>
    from .utils import get_logger, get_nodes_info, get_rand_id, get_neighbor
  File "/root/magnet-dht/magnet_dht/utils.py", line 55
    yield (nid, ip, port)
SyntaxError: 'return' with argument inside generator
You have new mail in /var/spool/mail/root

**Comment by gewplay** [comment]
已解决，原因是python版本问题
