### ISSUE TITLE
我有个不明白的可以问一下吗~

### ISSUE THREAD

**Issue by ldoubil** [chenjiandongx/magnet-dht#8]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\magnet-dht-master\manage.py", line 8, in <module>
    from magnet_dht.parse_torrent import parse_torrent
  File "C:\Users\Administrator\Desktop\magnet-dht-master\magnet_dht\parse_torrent.py", line 8, in <module>
    from bencoder import bdecode
ImportError: cannot import name 'bdecode' from 'bencoder' (C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\bencoder.py)
这个报错是因为？因为我是刚开始学~可能这个问题会有点傻，不过拜托了=0=

**Comment by ldoubil** [comment]
难道是因为3.7不支持吗？不过还是感谢啦;-)~我再去查查资料，能回复当然最好啦~~
